### PUT update an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Mo Taamneh",
  "email": "testupdated@example.com",
  "address": "122 Jaffar-AlTayyar street",
  "dateOfBirth": "2002-08-07",

}

###